apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-submission-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aslamchandio/gcp-oidc-gitops-app-repo.git
    targetRevision: HEAD
    path: kustomize/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
