apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  namespace: argocd-prod
  labels:
    app: myapp1-pod
spec:
  template:
    spec:
      containers:
      - name: myapp1-container
        resources:
          requests:
            memory: "60Mi"
            cpu: "60m"
          limits:
            memory: "60Mi"
            cpu: "80m"
